databases:
  - name: hussein
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m JoKeRUB
    region: frankfurt
    envVars:
    
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DEVLO
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: hussein
          property: connectionString   
    autoDeploy: false
