databases:
  - name: amged
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: qython
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 qython.py
    region: frankfurt
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: DEVLO 
        sync: false
      - key: TERMUX
        sync: false
        fromDatabase:
          name: amged
          property: connectionString   
    autoDeploy: false
